### ISSUE TITLE
OSX Silicon-based installation

### ISSUE THREAD

**Issue by xavier7179** [bkryza/clang-uml#126]
On Silicon-based systems the tool cannot be installed the way you are showing.
Since homebrew separates the paths between intel and silicon based, you need to export everything related to ```/opt/homebrew/```. Plus, you also need to export another variable ```export LLVM_DIR=/opt/homebrew/opt/llvm/lib/cmake/llvm/```.

Eventually, but I did not touch it, the CMakeList.txt file is clearly wrong in searching for yaml-cpp for the same reason.

**Comment by bkryza** [comment]
@xavier7179 Thanks for the issue, unfortunately I only have access to a 9 year old MBP at the moment so I cannot test it on Apple Silicon.

In the end, did you manage to build it on your system, and if yes what options did you use?

**Comment by bkryza** [comment]
@xavier7179 Unlikely, the error `no translation units found` almost always means that the `glob` pattern in your `.clang-uml` does not match any source files from the `compile_commands.json`. 

Please recheck your `glob` patterns (or remove `glob` section completely - this will result in `clang-uml` traversing all translation units in your project - but for large codebase this will be slow).

**Comment by xavier7179** [comment]
I fear it will be challenging because I do not get any stacktrace after the rebuild, still the same message. Regarding the first request:

```
clang-uml 0.3.4-2-gc91fe43
Copyright (C) 2021-2023 Bartek Kryza <bkryza@gmail.com>
Built against LLVM/Clang libraries version: 16.0.3
Using LLVM/Clang libraries version: Homebrew clang version 16.0.3
```

as per the second one: I'm trying a package one (but I will need all them in the end)

**Comment by bkryza** [comment]
@xavier7179 I understand, the version looks ok - one more thing - if you run `clang-uml` with `-vvv` option - can you try to pin-point from the output on what line in the code it fails, for instance some very complicated template specialization?

Also is your code base  C++17 or higher?

**Comment by xavier7179** [comment]
Actually, the code I'm trying to analyze is C99/C11 and not C++ so I might be mistaken about the ```clang-uml``` support in there... right?

**Comment by bkryza** [comment]
I've added support for plain C recently and there even is a test case for it:

https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00057.md

but to be honest I have not actually tested C code bases thoroughly so far...

So 2 more ideas:
* can you try to run `make test` in `clang-uml` and see if it passes all test cases on your system?
* if they do, try to limit the `glob` pattern in your configuration file to a single translation unit, rerun and see if you're still getting the error. If not add another source file to the `glob` pattern and maybe try to find the one which is problematic - maybe then we can figure out which specific part of code is the problem...

**Comment by xavier7179** [comment]
many things going on I guess. Following that example, I was able to run with that configuration (but structures names and connection are missing). Then I run the tests: the 3/8 did not pass:

```
3/8 Test #3: test_cases .......................***Failed   32.53 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_cases is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
t00018
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[path]/clang-uml/tests/t00018/test_case.h:19
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

[path]/clang-uml/tests/t00018/test_case.h:19: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  The complexity of an attempted match against a regular expression exceeded a pre-set level.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
t00019
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[path]/clang-uml/tests/t00019/test_case.h:19
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

[path]/clang-uml/tests/t00019/test_case.h:19: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  The complexity of an attempted match against a regular expression exceeded a pre-set level.

[error] [tid 59615] [generator.h:361] Failed to render PlantUML directive due to unresolvable alias: NoSuchClass
===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
test cases:  102 |  100 passed | 2 failed
assertions: 2081 | 2079 passed | 2 failed
```

**Comment by bkryza** [comment]
@xavier7179 

> Following that example, I was able to run with that configuration (but structures names and connection are missing).

Can you rerun `clang-uml` with `-vvv` and share the log and `.clang-uml` config file (you can anonymize the file and struct names if it's an issue)?

Also I've released yesterday a new version (0.3.5), I've added a fix on the `yaml-cpp` on the Apple Silicon and improved exception handling slightly...

**Comment by xavier7179** [comment]
Sure, I found many things, probably not all related with the thread:

1. the 3rd test case is still not working on Apple Silicon
2. the structs comes out anonymous because the definitions is
```
typedef struct {
<fields>
} name_of_the_struct;
```
3. as per request I'm attaching all the files (a lot of anonymization on them) and it looks to me that the segmentation fault is probably due to the recursion on the standard libraries.
4. I confirm that the new version patches the Apple Silicon compilation (with the additional export I was mentioning before)

[outclass.txt](https://github.com/bkryza/clang-uml/files/11453429/outclass.txt)
[clang-uml.txt](https://github.com/bkryza/clang-uml/files/11453441/clang-uml.txt)

**Comment by bkryza** [comment]
@xavier7179 Thank you for this information!

The current `master` now has a fix for typedef'ed structs, I've also fixed 2 possible segfault places, but I can't tell if they were related to your issue.

As to the configuration file, I rewrote it taking into account that:
* `generate_system_headers` - is only applicable to `include` diagrams
* having no include/exclude filters in diagram definition is tricky as it means that `clang-uml` will add to the diagram __everything__ it finds in the dependencies of your code base - which might be what you want - but I doubt it. I've added a `paths` filter, which will only add declarations that were found under a specific filesystem path, relative to your `.clang-uml` file - here `app_path` - please adjust as necessary (e.g. replace with `src` if that's where your sources are in your project directory)

```yaml
compilation_database_dir: cmake-build-debug
output_directory: diagrams
comment_parser: plain
debug_mode: true
diagrams:
  app_class:
    type: class
    include:
      paths: [app_path]
  app_package:
    type: package
    include:
      paths: [app_path]
  app_include:
    type: include
    generate_system_headers: false
    include:
      paths: [app_path]
```

If you still get segmentation fault, please run each diagram separately:

```bash
clang-uml --query-driver . -n app_class -vvv 
```

The option `--query-driver .` on macOS ensures that the compilation database has proper system paths, which sometimes can be an issue...

**Comment by bkryza** [comment]
@xavier7179 ok so the final solution is to use the `lldb` debugger to track down the exact line where the segfault occurs (adjust `clang-uml` arguments after `--` as necessary):

```bash
lldb debug/src/clang-uml -- -vvv --query-driver . -n my_diagram
```

then in the `(lldb)` prompt type `run` and hit enter.

When `clang-uml` crashes, type `bt` and enter and the stack trace should show the line in the `clang-uml` source which caused the crash - once we know that it should be possible to figure out what the bug is...

**Comment by xavier7179** [comment]
@bkryza sure here it is:

```
frame #0: 0x0000000106e9a58c libclang-cpp.dylib`clang::DeclContext::getEnclosingNamespaceContext() + 8
    frame #1: 0x00000001005cdba4 clang-uml`clanguml::package_diagram::visitor::translation_unit_visitor::find_relationships(this=0x0000600002108510, type=0x000000016fe858b8, relationships=size=0, relationship_hint=kAssociation) at translation_unit_visitor.cc:393:41
    frame #2: 0x00000001005cd7e0 clang-uml`clanguml::package_diagram::visitor::translation_unit_visitor::find_relationships(this=0x0000600002108510, type=0x000000016fe85950, relationships=size=0, relationship_hint=kAssociation) at translation_unit_visitor.cc:319:9
    frame #3: 0x00000001005cd694 clang-uml`clanguml::package_diagram::visitor::translation_unit_visitor::VisitFunctionDecl(this=0x0000600002108510, function_declaration=0x0000000102a6fee8) at translation_unit_visitor.cc:116:13
    frame #4: 0x000000010046e4bc clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::WalkUpFromFunctionDecl(this=0x0000600002108510, D=0x0000000102a6fee8) at DeclNodes.inc:433:1
    frame #5: 0x00000001003f7d90 clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::TraverseFunctionDecl(this=0x0000600002108510, D=0x0000000102a6fee8) at RecursiveASTVisitor.h:2226:1
    frame #6: 0x00000001003eea1c clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::TraverseDecl(this=0x0000600002108510, D=0x0000000102a6fee8) at DeclNodes.inc:433:1
    frame #7: 0x00000001004543b0 clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::TraverseDeclContextHelper(this=0x0000600002108510, DC=0x000000010283c630) at RecursiveASTVisitor.h:1489:7
    frame #8: 0x00000001003fc9d4 clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::TraverseTranslationUnitDecl(this=0x0000600002108510, D=0x000000010283c608) at RecursiveASTVisitor.h:1599:1
    frame #9: 0x00000001003ef01c clang-uml`clang::RecursiveASTVisitor<clanguml::package_diagram::visitor::translation_unit_visitor>::TraverseDecl(this=0x0000600002108510, D=0x000000010283c608) at DeclNodes.inc:645:1
    frame #10: 0x00000001003ede70 clang-uml`clanguml::common::generators::diagram_ast_consumer<clanguml::package_diagram::model::diagram, clanguml::config::package_diagram, clanguml::package_diagram::visitor::translation_unit_visitor>::HandleTranslationUnit(this=0x0000600002108500, ast_context=0x0000000102834600) at generators.h:156:18
    frame #11: 0x0000000106b99588 libclang-cpp.dylib`clang::ParseAST(clang::Sema&, bool, bool) + 708
    frame #12: 0x000000010881f7bc libclang-cpp.dylib`clang::FrontendAction::Execute() + 96
    frame #13: 0x00000001087a22b0 libclang-cpp.dylib`clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 580
    frame #14: 0x000000010893d5bc libclang-cpp.dylib`clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 376
    frame #15: 0x000000010893d314 libclang-cpp.dylib`clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>) + 252
    frame #16: 0x000000010893babc libclang-cpp.dylib`clang::tooling::ToolInvocation::run() + 992
    frame #17: 0x000000010893eb58 libclang-cpp.dylib`clang::tooling::ClangTool::run(clang::tooling::ToolAction*) + 2100
    frame #18: 0x00000001003ec3b4 clang-uml`std::__1::unique_ptr<clanguml::package_diagram::model::diagram, std::__1::default_delete<clanguml::package_diagram::model::diagram> > clanguml::common::generators::generate<clanguml::package_diagram::model::diagram, clanguml::config::package_diagram, clanguml::package_diagram::visitor::translation_unit_visitor>(db=0x0000600000201d20, name="app_package", config=0x0000000104033018, translation_units=size=21, (null)=true) at generators.h:248:27
    frame #19: 0x0000000100266200 clang-uml`void clanguml::common::generators::detail::generate_diagram_impl<clanguml::config::package_diagram>(od="/app_path/diagrams", name="app_package", diagram=std::__1::shared_ptr<clanguml::config::diagram>::element_type @ 0x0000000104033018 strong=3 weak=1, db=0x0000600000201d20, translation_units=size=21, generators=size=1, verbose=true) at generators.cc:91:18
    frame #20: 0x0000000100265c30 clang-uml`clanguml::common::generators::generate_diagram(od="/app_path/diagrams", name="app_package", diagram=std::__1::shared_ptr<clanguml::config::diagram>::element_type @ 0x0000000104033018 strong=3 weak=1, db=0x0000600000201d20, translation_units=size=21, generators=size=1, verbose=true) at generators.cc:132:9
    frame #21: 0x00000001004fad14 clang-uml`clanguml::common::generators::generate_diagrams(this=0x0000600002103ac8)::$_1::operator()() const at generators.cc:173:21
    frame #22: 0x00000001004fac88 clang-uml`decltype(__f=0x0000600002103ac8)::$_1&>()()) std::__1::__invoke[abi:v15006]<clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1&>(clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1&) at invoke.h:394:23
    frame #23: 0x00000001004fac40 clang-uml`void std::__1::__invoke_void_return_wrapper<void, true>::__call<clanguml::common::generators::generate_diagrams(__args=0x0000600002103ac8)::$_1&>(clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1&) at invoke.h:479:9
    frame #24: 0x00000001004fac1c clang-uml`std::__1::__function::__alloc_func<clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1, std::__1::allocator<clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1>, void ()>::operator(this=0x0000600002103ac8)[abi:v15006]() at function.h:185:16
    frame #25: 0x00000001004f9990 clang-uml`std::__1::__function::__func<clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1, std::__1::allocator<clanguml::common::generators::generate_diagrams(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, clanguml::config::config&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<clanguml::common::compilation_database, std::__1::default_delete<clanguml::common::compilation_database> > const&, int, unsigned int, std::__1::vector<clanguml::common::generator_type_t, std::__1::allocator<clanguml::common::generator_type_t> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&)::$_1>, void ()>::operator(this=0x0000600002103ac0)() at function.h:359:12
    frame #26: 0x0000000100224154 clang-uml`std::__1::__function::__value_func<void ()>::operator(this=0x0000600000c00608)[abi:v15006]() const at function.h:512:16
    frame #27: 0x0000000100224104 clang-uml`std::__1::function<void ()>::operator(this=0x0000600000c00608)() const at function.h:1197:12
    frame #28: 0x0000000100646b74 clang-uml`decltype(__f=0x0000600000c00608)>&>()()) std::__1::__invoke[abi:v15006]<std::__1::function<void ()>&>(std::__1::function<void ()>&) at invoke.h:394:23
    frame #29: 0x0000000100646718 clang-uml`std::__1::__packaged_task_func<std::__1::function<void ()>, std::__1::allocator<std::__1::function<void ()> >, void ()>::operator(this=0x0000600000c00600)() at future:1694:12
    frame #30: 0x0000000100648fac clang-uml`std::__1::__packaged_task_function<void ()>::operator(this=0x000000016fe86ee0)() const at future:1876:12
    frame #31: 0x00000001006426e8 clang-uml`std::__1::packaged_task<void ()>::operator(this=0x000000016fe86ee0)() at future:2068:9
    frame #32: 0x0000000100641e34 clang-uml`clanguml::util::thread_pool_executor::worker(this=0x000000016fdfe1a8) at thread_pool_executor.cc:66:13
    frame #33: 0x0000000100644be0 clang-uml`decltype(__f=0x0000600000201d68, __a0=0x0000600000201d78).*std::declval<void (clanguml::util::thread_pool_executor::*)()>()()) std::__1::__invoke[abi:v15006]<void (clanguml::util::thread_pool_executor::*)(), clanguml::util::thread_pool_executor*, void>(void (clanguml::util::thread_pool_executor::*&&)(), clanguml::util::thread_pool_executor*&&) at invoke.h:359:23
    frame #34: 0x0000000100644b20 clang-uml`void std::__1::__thread_execute[abi:v15006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (clanguml::util::thread_pool_executor::*)(), clanguml::util::thread_pool_executor*, 2ul>(__t=size=3, (null)=__tuple_indices<2UL> @ 0x000000016fe86f7f)(), clanguml::util::thread_pool_executor*>&, std::__1::__tuple_indices<2ul>) at thread:290:5
    frame #35: 0x0000000100644544 clang-uml`void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (clanguml::util::thread_pool_executor::*)(), clanguml::util::thread_pool_executor*> >(__vp=0x0000600000201d60) at thread:301:5
    frame #36: 0x00000001ac6cffa8 libsystem_pthread.dylib`_pthread_start + 148
```

**Comment by bkryza** [comment]
@xavier7179 Thank you, this is now fixed in `master`. 

Please note however, that generating `package` diagrams from purely C99/C11 code base will always generate empty diagrams, since the package diagram generator only takes into account C++ namespaces as packages at the moment.

I am considering adding an option to package diagram generator to also consider subdirectories as packages in the package diagrams, but it is not available yet. Also, if you have an idea of what should a package diagram contain for a C codebase please let me know...

**Comment by xavier7179** [comment]
@bkryza I confirm that the bug is now solved, and the package is empty.

I'm not a super expert on diagrams, but from a C standpoint, the only UML diagram that is missing is one relating all structures to their dependencies w.r.t. functions (if I got it right, it should be an "association" one)... but that's my guessing.

**Comment by bkryza** [comment]
Thanks, I'll consider it - currently free functions (i.e. not methods) are completely ignored except for `sequence` diagrams...
